### ISSUE TITLE
`asdf global elixir path:...` fails

### ISSUE THREAD

**Issue by marcandre** [asdf-vm/asdf-elixir#101]
I built a custom copy of `elixir` and I am trying to make it available with `asdf`, but I get an error.

Did I misread [the docs](https://github.com/asdf-vm/asdf-elixir#using-the-cli)?

```
$ asdf global elixir path:/Users/mal/elixir/bin/elixir
version path:/Users/mal/elixir/bin/elixir is not installed for elixir
```

Yet everything else looks right:
```
$ /Users/mal/elixir/bin/elixir --version
Erlang/OTP 23 [erts-11.2.1] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe] [dtrace]

Elixir 1.13.0-dev (fb92f7a) (compiled with Erlang/OTP 23)

$ asdf --version
v0.8.0

$ asdf plugin list elixir --urls --refs
elixir                       https://github.com/asdf-vm/asdf-elixir.git master e6e9a9e
erlang                       https://github.com/asdf-vm/asdf-erlang.git master f850959
```

**Comment by Stratus3D** [comment]
@marcandre is `/Users/mal/elixir/bin/elixir` a directory? Or is it the location of the `elixir` executable? I think as the name implies it needs to be the path to the elixir installation's root directory, which would be the directory containing the `bin` directory. I think you may need to use `asdf global elixir path:/Users/mal/elixir`

**Comment by marcandre** [comment]
Oh, that works 🤦‍♂️. I actually tried with the directory first, but got confused as I thought it would do something else than just point to it, but behavior makes sense. Sorry for the noise and thanks for the answer

**Comment by Stratus3D** [comment]
@marcandre feel free to create a PR if you think the information in the readme could be improved. The current readme doesn't say much about what the path should be.

**Comment by marcandre** [comment]
1) Ah, I have an idea what confused me too, path must be absolute.

```
$ asdf local elixir path:~/elixir
version path:~/elixir is not installed for elixir
```

Is this a bug (or else I can propose a PR to specify this).

2) Another thing that could be helpful (which is what I was actually looking for) is: instead of switching the current version of elixir to a given path, I'd like to name that path in the available versions of elixir. 

I.e. instead of `asdf local elixir path:/Users/mal/elixir` I'd like to say `asdf local elixir dev` for example. Should adding a symbolic link in the right directory work?

**Comment by Stratus3D** [comment]
1. Yes that isn't very nice. It would be better if we handled the `~` properly. As a workaround you can use `$HOME`. This will need to be fixed in asdf core. The elixir plugin doesn't actually handle any of that logic. Feel free to create a ticket for this if this isn't one already.
2. We don't support aliases because they can easily get confusing. Typically versions aren't changed very often so this isn't much of a problem. If you need to repeat the same command multiple times a shell alias or function is probably the easiest way to make the command easier to type. `alias myelixir='asdf local elixir path:/Users/mal/elixir'`.

I am updating the readme to hopefully make it easier to understand.

**Comment by Stratus3D** [comment]
I created https://github.com/asdf-vm/asdf/issues/941 for this.
