### ISSUE TITLE
Consider always building from source

### ISSUE THREAD

**Issue by michalmuskala** [asdf-vm/asdf-elixir#27]
Right now a precompiled package is used when possible. This is great for the speed of building Elixir but has some other issues. 

The most significant one is related to changes in OTP 20. OTP 20 changed the format of debug information. This allows features like `Exception.blame` to work. That said, Elixir supports OTP versions since 18, so the precompiled package is always compiled on the lowest supported version for compatibility. Unfortunately, this means, even when users have OTP 20, they will use code compiled on OTP 18 and won't get things like `Exception.blame` for modules from the standard library.

Always compiling Elixir from source should solve this issue. It shouldn't also be a big issue timewise, given asdf already compiles Erlang from source. Compiling Elixir is almost instantaneous compared to that.

It might be possible we'll get precompiled Elixir for each OTP version, but always compiling from source should be a more future-proof solution.

**Comment by ericmj** [comment]
We provide precompiled Elixir packages for specific OTP versions here: https://github.com/hexpm/bob/blob/master/README.md#elixir-builds.

**Comment by michalmuskala** [comment]
Given we have those now, I believe using them would be the best idea.

**Comment by ericmj** [comment]
@vic This looks great but I am afraid if we don't default to using the version precompiled for the users OTP few people will get the proper precompiled versions since it would require going here and reading the docs. What do you think about defaulting to using the `-otp-` version and falling back to normal if the URL 404s?

**Comment by vic** [comment]
In order to use the `-otp-` version by default, and if no `-otp-` postfix was explicitly added by the user, the installer would need to ask `asdf` for the currently selected Erlang version. So for example for Erlang `18.2.1` and `18.3` we would have to use `-otp-18` as there seems to be no Elixir precompiled versions except for the major OTP version. 

This would require the user to have previously set the correct erlang version on their `.tool-versions` file before trying to install Elixir.

So given the following `.tool-versions` in a project A

```
erlang 19.3
elixir 1.5.0-rc0
```

the installed elixir would be precompiled for `-otp-19` but the version is still known as just `1.5.0-rc0`

Now given you had another `.tool-versions` in project B

```
erlang 20.0
elixir 1.5.0-rc0
```

the problem here would be that elixir `1.5.0-rc0` would look like already installed (precompiled for otp 19) and not for OTP 20.

So I'm thinking it might be better to keep things explicit, and actually require users to specify the otp release as it's part of the version string for both asdf and bob's zips.

**Comment by ericmj** [comment]
Good points @vic, thanks for elaborating.

**Comment by enilsen16** [comment]
Since [bob](https://github.com/hexpm/bob) only builds against official versions of OTP, this means you can't compile elixir against OTP master using asdf. 😕

**Comment by ericmj** [comment]
@enilsen16 Set OTP master in your path and build a git reference wit: `asdf install elixir ref:master`.
